//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentStatu
    {
        public int intCode { get; set; }
        public int intStudentCode { get; set; }
        public string strStatus { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
    }
}
